### ISSUE TITLE
[BUG Prostar2]

### ISSUE THREAD

**Issue by Brugiere38** [edyp-lab/Prostar2#104]
**Describe the bug**
au moment de l'import du fichier XL, je passe toutes les étapes quand j'arrive a "order par condition" il freeze.....
si je ne demande pas d'order par condition je peux passer a la dernière étape.
Dans ce cas quand je fais save, il freeze....

**Comment by samWieczorek** [comment]
Pbm dû à un bug dans le package QFeatures (je lui fais un ticket).
Pbm résolu dans Prostar2
