### ISSUE TITLE
L'arbre des Cell metadata ne s'ouvre pas

### ISSUE THREAD

**Issue by mariannetardif** [edyp-lab/Prostar2#72]
Après conversion du fichier "Proline_12samples15s.xlsx" (OK) : LemoigneTest1.qf
Filtre :  A l'étape du "Cell metadata filtering", l'arbre des tags ne s'ouvre pas quand on clique sur la vignette. Impossible de définir un filtre.
Fichiers ici (comme d'hab. ) :S:\342-Projets_BGE\342.1-EDyP\342.1.6-Management\342.1.6.2-Documents\Groupes_de_Travail\ProstarV2\Lemoigne-TESTS

**Comment by samWieczorek** [comment]
A reessayer avec la dernière version disponible sur Github

**Comment by mariannetardif** [comment]
C'est ok
